### ISSUE TITLE
Cloverage hangs after running to completion

### ISSUE THREAD

**Issue by AeroNotix** [JacekLach/cloverage#24] opened 2014-01-21 09:42 UTC
Hi,

When I run `lein cloverage` (version 1.0.2) it hangs after creating the HTML output file. I've seen this across a number of machines.

**Comment by JacekLach** [comment] 2014-01-21 13:41
Hm. Can you share the project that you're testing?

My intuition would be that your code creates threads / threadpools that don't shut down after tests are ran. In that case this is probably best solved the same way as https://github.com/lshift/cloverage/issues/25 - by explicitly shutting down the jvm after running tests (rather than just returning from main, as it currently does)

**Comment by AeroNotix** [comment] 2014-01-21 13:42
On 21/01/14 14:41, Jacek Lach wrote:

> Hm. Can you share the project that you're testing?
> 
> My intuition would be that your code creates threads / threadpools 
> that don't shut down after tests are ran. In that case this is 
> probably best solved the same way as lshift#25 
> https://github.com/lshift/cloverage/issues/25 - by explicitly 
> shutting down the jvm after running tests (rather than just returning 
> from main, as it currently does)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/JacekLach/cloverage/issues/24#issuecomment-32885520.
> 
> Hi,

No, this is a closed-source project. I'll look into lshift#25 and get 
back to you. I don't explicitly create any threads but I use several 
libraries which may.

Thanks!

Aaron

**Comment by JacekLach** [comment] 2014-01-21 14:06
Hi Aaron.

Can you see if that fixes your issue?
Grab the `exit-after-tests` branch from this repo and run `lein install` in the `cloverage` directory, then run `CLOVERAGE_VERSION=1.0.4-SNAPSHOT lein cloverage` in your project?

Thanks!
- J

**Comment by AeroNotix** [comment] 2014-01-21 14:07
@JacekLach testing now.

**Comment by frankshearar** [comment] 2014-01-21 14:10
The change looks good. Keen to hear if it solves the problem!

(Much easier to read the diff if you ignore whitespace, of course: https://github.com/JacekLach/cloverage/commit/55aea266edd18dfce3e59504b76486acee30fd97?w=1)

**Comment by AeroNotix** [comment] 2014-01-21 14:12
@JacekLach I get: https://gist.github.com/AeroNotix/c17851c03c16a8ef94e8

**Comment by JacekLach** [comment] 2014-01-21 14:26
Hm. I'll have to look at it later then - about to leave for work.

It seems unrelated to this change - can you try one more thing? Same steps as before, except now on the master branch:

``` bash
    git checkout master
    (cd cloverage && lein install)
    cd $my-project-dir
    CLOVERAGE_VERSION=1.0.4-SNAPSHOT lein cloverage
```

I think the error is probably caused by something from https://github.com/lshift/cloverage/pull/27. If so, it'd be _really cool_ if you could try to locate the issue and produce a reproduction example, or at least describe generally if there's anything unusual about the code that tries to call `parse-opts`.

Ta

**Comment by JacekLach** [comment] 2014-01-21 14:27
Also ignore the 4887ebe 'reference', it's just github being confused about different repositories.

**Comment by AeroNotix** [comment] 2014-01-22 20:26
@JacekLach similar problem on master branch, "IllegalAccessError: parse-opts does not exist."

**Comment by AeroNotix** [comment] 2014-01-22 20:41
FWIW -- it turned out a library I was using was spawning threads which weren't being killed. So the problem is "solved" for me, but whether you want to continue to debug this is up to you.

**Comment by JacekLach** [comment] 2014-01-22 22:49
Right, thanks for coming back. The 'parse-opts' problem is unrelated to this issue, rather it's caused by a different improvement that's already been merged into 1.0.4.

My guess was the instrumentation was messing up either the `ns` form, or the code that declares `parse-opts`. Unfortunately I couldn't reproduce that with the simple attempts I made.

Could you tell me how does the (ns) form look in the `payments.core` namespace? Is there anything unusual there, for example it not being the first form in the file? Is `parse-opts` your code or does it come from `tools.cli`?

Any hints you can provide will be very helpful in debugging that issue. Otherwise I'm afraid I'll have to wait for someone else to encounter it to get the fix.

**Comment by AeroNotix** [comment] 2014-01-22 22:51
Aha! That was a good clue. My application contains parse-opts as well, weird. Could the instrumentation be going AWOL with the clashing parse-opts?

``` clojure

(ns payments.core
  (:use [compojure.core :only [defroutes GET POST]]
        [payments.sso.middleware :only [ensure-auth-cookie-middleware
                                        avail-auth-cookie-middleware]]
        [payments.http.request :only [parse-cookies-middleware]]
        [clojure.java.io])
  (:require [clojure.tools.cli :refer [parse-opts]]
            [compojure.handler :as handler]
            [compojure.route :as route]
            [payments.configuration.server :as ssl-config]
            [payments.configuration.db :as db-config]
            [payments.configuration.identity :as identity-config]
            [payments.configuration.properties :refer [merge-config!]]
            [payments.db :as db]
            [ring.adapter.jetty :as jetty]
            [clj-yaml.core :as yaml]))
```

**Comment by JacekLach** [comment] 2014-01-22 22:51
Nevermind that, I got a repro now.

**Comment by JacekLach** [comment] 2014-01-22 22:52
Yes, I think some kind of classpath clash is the issue. Thanks anyway!

I'll open a new issue for that bug.

**Comment by AeroNotix** [comment] 2014-01-22 22:52
Wicked. Cheers!

**Closed as completed by JacekLach** 2014-01-22 22:52 UTC

**Comment by JacekLach** [comment] 2014-01-22 23:02
@AeroNotix - feel free to email me if you want to chat (see my github profile), but let's not spam this issue :)
